# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pip install --upgrade pip; pip install notebook pandas numpy matplotlib # runs during prebuild
  - command: jupyter trust *.ipynb; jupyter notebook --ip=*
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-browser

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: true